### ISSUE TITLE
Wrong Fajr and Sunrise times are being reported for some time zones

### ISSUE THREAD

**Issue by azzamsa** [insha/salah#1] opened 2020-09-25 00:55 UTC
I'm struggling to pass more config. I've pretty good result with the code below:

```rust
fn get_prayers_time() -> Result<salah::PrayerTimes, String> {
    let city = Coordinates::new(-7.1605439, 113.4826273);
    let date = Utc::today();
   let params = Configuration::with(Method::Singapore, Madhab::Shafi);    
    let prayers = PrayerSchedule::new()
        .on(date)
        .for_location(city)
        .with_configuration(params)
        .calculate();
    return prayers;
}

```

Unfortunately, the fajr and sunrise time is wrong. But other time are correct:

```
Fajr: 7:59 AM <--- it should 03:59 AM
Sunrise: 7:14 AM <---
Dhuhr: 11:19 AM
Asr: 2:29 PM
Maghrib: 5:22 PM
Isha: 6:29 PM
Qiyam: 3:07 AM
```

I can get my Python version with [PyIslam](https://github.com/abougouffa/pyIslam) right. But I think need I need to pass more config to get this rust version right.

**I've tried following ways**, but can't get it right. Because I don't find any example in the [docs](https://docs.rs/salah/0.4.2/salah/struct.Configuration.html) and readme.

``` diff
fn get_prayers_time() -> Result<salah::PrayerTimes, String> {
    let city = Coordinates::new(-7.1605439, 113.4826273);
    let date = Utc::today();
+    let params = Configuration::new()
+        .with(Method::Singapore, Madhab::Shafi);
    let prayers = PrayerSchedule::new()
        .on(date)
        .for_location(city)
        .with_configuration(params)
        .calculate();
    return prayers;
}

```

Also, I want to pass with other params such: `HighLatitudeRule`. 

How can I do this?

Thank you for salah.

**Comment by RagibHasin** [comment] 2020-09-26 06:31
Assalamu 'Alaykum, dear brother @azzamsa.

The problem with wrong Fajr time is due to a bug in `SolarTime::setting_hour` that I fixed in my fork with RagibHasin@ea23f0cae0cc2485a2ee238c8240170b26bb6f63.

And this crate's upper level `mod.rs` is missing the export for `HighLatitudeRule` that I also fixed in my fork with RagibHasin@941099f5a310f2bab24b21c728274c5d2721fa7a.

Please try it from my fork and comment the results. If it works as expected I would make a pull request.

**Comment by azzamsa** [comment] 2020-09-26 07:08
Subhanallah. Yes, I am waiting for the answer for hours while developing my app at the top of this library. I am worried that I will not get the answer soon. So I try to find out myself (as a Rust newbie).

1) I want to try to use `HighLatitudeRule` as the [upsteam test data](https://github.com/batoulapps/adhan-testdata/blob/master/Times/Ankara-Turkey.json) has. Hoping it will be fixed the fajr and sunrise time.

So I try hard to find the variation of params to get it right. In the end, it was not. So I try to clone the code and find out that `HighLatitudeRule` is not [exposed](https://github.com/insha/salah/blob/master/src/lib.rs#L40).

I have it patched, and try with a different value: `TwilightAngle`, `SeventhOfTheNight`. Nothing change. I worried [it's not implemented yet](https://github.com/insha/salah/blob/5c13207ddcfb003a7538bfcbd440729dfc152395/src/models/high_altitude_rule.rs#L13) as there is no `impl`

``` rust
    let params = Configuration::new(20.0, 18.0).method(Method::Singapore).madhab(Madhab::Shafi)
        .high_latitude_rule(HighLatitudeRule::TwilightAngle)
        .done();

```

2) I figure out to use an additional keyword (sadly, it doesn't exist in the docs). So I figure it out by reading the function signature.

```rust
        let params = Configuration::new(20.0, 18.0)
        .method_adjustments(TimeAdjustment::new(-211, -211, 0, 0, 0, 0))
        .done();
```

---

> The problem with the wrong Fajr time is due to a bug in SolarTime::setting_hour that I fixed in my fork with RagibHasin/salah-rs@ea23f0c.

Alhamdulillah. will try it right away.

**Comment by azzamsa** [comment] 2020-09-26 07:29
@RagibHasin Alhamdulillah, worked like a charm. May Allah grant you a *amal jariya*.

the output:
![image](https://user-images.githubusercontent.com/17734314/94335248-6fc54300-0004-11eb-83b8-653ccd764204.png)

reference: (not that it has beed added 2 minutes for *Ihtiyati*, so our result is definitely correct)
![image](https://user-images.githubusercontent.com/17734314/94335266-8d92a800-0004-11eb-9295-693181150494.png)

**Comment by azzamsa** [comment] 2020-09-26 07:31
@RagibHasin I see each 11 new commit in your repo. most of them are interesting and new. Actually I am corious about those new feature such as: 1) using schemars, etc.

One thing I note is that: IMHO, .vscode setting should not be pushed in public dir :)

**Comment by azzamsa** [comment] 2020-09-26 07:46
Thanks @RagibHasin https://github.com/azzamsa/salah/commit/89c234d67aee415cd50c8069aeffd491edd88ad2

**Comment by RagibHasin** [comment] 2020-09-26 09:24
> @RagibHasin I see each 11 new commit in your repo. most of them are interesting and new. Actually I am corious about those new feature such as: 1) using schemars, etc.

I am developing an app that generates UI based on JSON schema, that's why I've added `schemars`.

> One thing I note is that: IMHO, .vscode setting should not be pushed in public dir :)

Didn't know that! Will remove it before PR then.

JazakAllahu Khair.

**Comment by RagibHasin** [comment] 2020-09-26 09:27
Or should you send the PR, with less clutter and all? My other modifications won't be much publicly needed I think.

**Comment by azzamsa** [comment] 2020-09-26 09:34
> Didn't know that! Will remove it before PR then.

some people did it, But I think it's not a good practice since not everyone use vscode.

> Or should you send the PR, with less clutter and all? My other modifications won't be much publicly needed I think.

I don't think the maintainer is active, what do you think?

**Comment by RagibHasin** [comment] 2020-09-26 09:51
> I don't think the maintainer is active, what do you think?

His last activity was in June'20 and before that March'20. Seems like he is not frequently active. But it won't hurt to send a PR.

**Comment by azzamsa** [comment] 2020-09-26 10:44
> His last activity was in June'20 and before that March'20. Seems like he is not frequently active. But it won't hurt to send a PR.

Done.

---

> I have tried with a different value: TwilightAngle, SeventhOfTheNight. Nothing change. I worried it's not implemented yet as there is no `impl`.

@RagibHasin is `HighLatitudeRule` not implemented?

---

I've some question regarding this salah library. How can I ask you some question? I don't see the issue page on your repo, or shoud we use other medium? thanks.

**Comment by RagibHasin** [comment] 2020-09-26 11:29
> I've some question regarding this salah library. How can I ask you some question? I don't see the issue page on your repo, or shoud we use other medium? thanks.

Forked repos don't have issues.

> is HighLatitudeRule not implemented?

I don't know, as I didn't need high latitude computing. But we should look at it.

---

As for communication email is fine to me though some IM service would be better.

**Comment by insha** [comment] 2021-01-11 23:37
Duplicate of #6 ; therefore closing this one.

**Closed as completed by insha** 2021-01-11 23:37 UTC
Labels: bug, question
